project:
  type: website
  #resources:
  #    - "static/**"
  #Static doesn't work for some reason. just use resources to resolve the issue.
  
website:
  title: "JackSalazar"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: blog/index.md
        text: Blog

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true



