project:
  type: website
  #resources:
  #    - "static/**"
  #Static doesn't auto detect for some reason. Just use resources to resolve the issue. Resources also lets you name the directory whatever you want.
  
website:
  title: "Jack Salazar"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: blog/index.md
        text: Blog
    right: 
      #- href: contact/index.md
      #  text: Contact
      - icon: github
        href: https://github.com/JackSalazar
  #announcement:
  #  icon: info-circle
  #  dismissable: true
  #  content: **Alert** - Website cosmetic revamp coming soon. Preorder today!
  #  type: info
  #  position: below-navbar

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true



