project:
  type: website

website:
  title: "JackSalazar"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: blog/index.qmd
        text: Blog
resources:
      - "static/*"
format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true



