project:
  type: website
  #resources:
  #    - "static/**"
  #Static doesn't auto detect for some reason. Just use resources to resolve the issue. Resources also lets you name the directory whatever you want.
  
website:
  title: "Jack Salazar"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: blog/index.md
        text: Blog
    right: 
      #- href: contact/index.md
      #  text: Contact
      - icon: github
        href: https://github.com/JackSalazar
  announcement:
    icon: info-circle
    dismissable: true
    content: Did you ever hear the tragedy of Darth Plagueis the Wise? I thought not. It's not a story the Jedi would tell you. It's a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life... He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. It's ironic he could save others from death, but not himself.
    type: primary
    position: below-navbar

format:
  html:
    theme:
      # See: https://quarto.org/docs/output-formats/html-themes.html
      light: default
      dark: cyborg
    css: styles.css
    toc: true



